import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./lib/**/*.{ts,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#f6f3ee",
        surface: "#fcf9f4",
        "on-secondary": "#ffffff",
        "surface-tint": "#885215",
        "surface-variant": "#e5e2dd",
        "on-error": "#ffffff",
        "on-primary-fixed": "#2d1600",
        "surface-container": "#f0ede9",
        outline: "#847467",
        "on-tertiary": "#ffffff",
        "primary-fixed": "#ffdcbf",
        "on-surface-variant": "#524439",
        "on-surface": "#1c1c19",
        "on-error-container": "#93000a",
        "on-tertiary-container": "#fffbff",
        "secondary-fixed": "#ede1d1",
        "outline-variant": "#d6c3b4",
        "on-secondary-container": "#6b6357",
        "inverse-on-surface": "#f3f0eb",
        "on-primary-container": "#fffbff",
        "error-container": "#ffdad6",
        error: "#ba1a1a",
        "primary-fixed-dim": "#ffb873",
        "on-secondary-fixed-variant": "#4d463a",
        "tertiary-fixed-dim": "#ddc1aa",
        background: "#fcf9f4",
        "surface-container-high": "#ebe8e3",
        "primary-container": "#a2672a",
        "on-secondary-fixed": "#201b11",
        "surface-container-lowest": "#ffffff",
        "surface-bright": "#fcf9f4",
        secondary: "#655d51",
        "surface-dim": "#dcdad5",
        "tertiary-fixed": "#fbddc5",
        "on-primary-fixed-variant": "#6a3b00",
        "tertiary-container": "#87705c",
        "inverse-surface": "#31302d",
        "inverse-primary": "#ffb873",
        "on-tertiary-fixed-variant": "#564331",
        "secondary-container": "#ede1d1",
        "on-background": "#1c1c19",
        tertiary: "#6d5845",
        "surface-container-highest": "#e5e2dd",
        "on-primary": "#ffffff",
        "secondary-fixed-dim": "#d0c5b6",
        "on-tertiary-fixed": "#27180a",
        primary: "#854f12",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "container-max": "1400px",
        gutter: "32px",
        "section-gap": "150px",
        "margin-mobile": "24px",
        "stack-sm": "20px",
        "stack-md": "40px",
        base: "8px",
      },
      fontFamily: {
        display: ["var(--font-playfair)", "serif"],
        body: ["var(--font-inter)", "sans-serif"],
      },
      fontSize: {
        "headline-sm": ["clamp(20px, 3.5vw, 30px)", { lineHeight: "1.4", fontWeight: "600" }],
        display: [
          "clamp(36px, 7.5vw, 80px)",
          { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "headline-md": ["clamp(26px, 4.5vw, 40px)", { lineHeight: "1.3", fontWeight: "600" }],
        "headline-lg-mobile": [
          "clamp(24px, 5.5vw, 38px)",
          { lineHeight: "1.2", fontWeight: "700" },
        ],
        "body-md": ["clamp(15px, 2vw, 18px)", { lineHeight: "1.6", fontWeight: "400" }],
        "body-lg": ["clamp(16px, 2.2vw, 20px)", { lineHeight: "1.7", fontWeight: "400" }],
        "label-sm": [
          "clamp(11px, 1.2vw, 13px)",
          { lineHeight: "1.2", letterSpacing: "0.1em", fontWeight: "600" },
        ],
        "headline-lg": [
          "clamp(26px, 5vw, 60px)",
          { lineHeight: "1.2", fontWeight: "700" },
        ],
        "label-md": [
          "clamp(14px, 1.5vw, 16px)",
          { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "500" },
        ],
      },
      keyframes: {
        float: {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-16px)" },
        },
        "pulse-glow": {
          "0%, 100%": { opacity: "0.3" },
          "50%": { opacity: "0.6" },
        },
      },
      animation: {
        float: "float 6s ease-in-out infinite",
        "float-slow": "float 9s ease-in-out infinite",
        "pulse-glow": "pulse-glow 4s ease-in-out infinite",
      },
    },
  },
  plugins: [],
};

export default config;
